version: '3.4'

services:
  temperatureautomation.api:
    image: ${DOCKER_REGISTRY-}temperatureautomationapi
    build:
      context: .
      dockerfile: TemperatureAutomation.Api/Dockerfile
    ports:
      - 2080:8080
      - 2443:8081
    environment:
      BrewFather__User: "##"
      BrewFather__Key: "##"
      Shelly__Key: "##"
      Shelly__Server: "##"
      Shelly__DeviceId: "##"
      MinTemp: "18.5"
      MaxTemp: "19.5"